# GitHub Pages Jekyll Configuration for Cevehak
# This enables clean URLs without .html extensions

# Site settings
title: "Cevehak - خدمات السير الذاتية والمواقع المهنية"
description: "نحول خبراتك إلى موقع ويب احترافي يميزك عن الآخرين"
baseurl: ""
url: "https://cevehak.online"

# Clean URLs - removes .html extensions
permalink: pretty

# Include views directory for processing
include:
  - "views"

# Process all HTML files in views directory
defaults:
  - scope:
      path: "views"
      type: "pages"
    values:
      layout: none

# GitHub Pages safe plugins only
plugins:
  - jekyll-relative-links

# Relative links settings
relative_links:
  enabled: true
  collections: false

# Exclude files from processing
exclude:
  - README.md
  - node_modules/
  - .gitignore
  - gh-pages/

# Markdown processor (GitHub Pages default)
markdown: kramdown

# Syntax highlighting (GitHub Pages default)
highlighter: rouge

# Safe mode for GitHub Pages
safe: true

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
